### PR TITLE
Add variable for gossip port

### PR DESCRIPTION
**Pull request by TeeVeeEss**
Port 15600 could already be in use for e.g. your mainnet node. With this new variable in .env it should be easy to switch to another port,

### CODE REVIEW

**Comment by JannemanDev** [comment]
Shouldn't this also contain the variable?
```
#EXTERNAL_P2P_MULTIADDRESS=/dns/${NODE_HOST}/tcp/15600
```

**Comment by TeeVeeEss** [comment]
> Shouldn't this also contain the variable?
> 
> ```
> #EXTERNAL_P2P_MULTIADDRESS=/dns/${NODE_HOST}/tcp/15600
> ```

No. The internal port 15600 stays the same. Only the external port changes to the desired one.

**Comment by TeeVeeEss** [comment]
Added the port section on top to be able to use it later in the .env file. 
Not sure if `--p2p.autopeering.externalMultiAddresses=${EXTERNAL_P2P_MULTIADDRESS:-}` can be used in all versions though.

**Comment by muXxer** [comment]
I cleaned it a bit up :trollface:

**Pull request merged**
